(()=>{'use strict';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
function theme(mode){document.documentElement.classList.toggle('dark',mode==='dark');document.documentElement.classList.toggle('sepia',mode==='sepia');$$('[data-theme]').forEach(b=>b.setAttribute('aria-label',mode==='dark'?'Тема: ночь':mode==='sepia'?'Тема: сепия':'Тема: день'))}
$$('[data-theme]').forEach(b=>b.addEventListener('click',()=>theme(document.documentElement.classList.contains('dark')?'light':'dark')));
$$('[data-play]').forEach(b=>b.addEventListener('click',()=>{$$('[data-play]').forEach(x=>x.classList.toggle('playing',!x.classList.contains('playing')))}));
$$('[data-save]').forEach(b=>b.addEventListener('click',()=>{const on=b.getAttribute('aria-pressed')!=='true';$$('[data-save]').forEach(x=>{x.classList.toggle('is-saved',on);x.setAttribute('aria-pressed',String(on))})}));
let active=null,returnFocus=null;function openSheet(id){const el=$(id);if(!el)return;returnFocus=document.activeElement;active=el;el.classList.add('open');el.setAttribute('aria-hidden','false');document.body.classList.add('lock');requestAnimationFrame(()=>el.querySelector('button,input,[href]')?.focus())}function closeSheet(el=active){if(!el)return;el.classList.remove('open');el.setAttribute('aria-hidden','true');document.body.classList.remove('lock');active=null;returnFocus?.focus?.()}
$$('[data-open]').forEach(b=>b.addEventListener('click',()=>openSheet(b.dataset.open)));$$('[data-close]').forEach(b=>b.addEventListener('click',()=>closeSheet(b.closest('.sheet-backdrop'))));$$('.sheet-backdrop').forEach(x=>x.addEventListener('click',e=>{if(e.target===x)closeSheet(x)}));
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeSheet();if(e.key==='Tab'&&active){const a=$$('button:not([disabled]),input,[href],[tabindex]:not([tabindex="-1"])',active).filter(x=>x.offsetParent!==null);if(!a.length)return;const f=a[0],l=a[a.length-1];if(e.shiftKey&&document.activeElement===f){e.preventDefault();l.focus()}else if(!e.shiftKey&&document.activeElement===l){e.preventDefault();f.focus()}}});
$$('.options').forEach(g=>g.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;g.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));if(b.dataset.settingTheme)theme(b.dataset.settingTheme)}));
$$('[data-accordion]').forEach(b=>b.addEventListener('click',()=>{const p=b.closest('[data-accordion-item]');p.classList.toggle('open');b.setAttribute('aria-expanded',String(p.classList.contains('open')))}));
const links=$$('[data-toc] a[href^="#"]'),sections=links.map(a=>$(a.getAttribute('href'))).filter(Boolean);let tick=false;function spy(){tick=false;let at=0;sections.forEach((s,i)=>{if(s.getBoundingClientRect().top<=innerHeight*.4)at=i});links.forEach((a,i)=>a.classList.toggle('active',i===at));$$('[data-current]').forEach(x=>x.textContent=links[at]?.textContent.trim()||'Содержание')}
addEventListener('scroll',()=>{if(!tick){tick=true;requestAnimationFrame(spy)}},{passive:true});spy();
$$('[data-filter]').forEach(b=>b.addEventListener('click',()=>{$$('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));const f=b.dataset.filter;$$('.catalog-card').forEach(c=>c.hidden=f!=='all'&&c.dataset.kind!==f)}));
const q=$('[data-search-input]');q?.addEventListener('input',()=>{const v=q.value.toLocaleLowerCase('ru');$$('.catalog-card').forEach(c=>c.hidden=!c.textContent.toLocaleLowerCase('ru').includes(v))});
})();
